[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

lib_deps =
    https://github.com/pschatzmann/arduino-audio-tools.git
    https://github.com/AlboSoc/arduino-wm8960

monitor_speed = 115200
upload_port = COM6
monitor_port = COM6
